included:
  - blueprint
  - Packages

excluded:
  - blueprint.xcodeproj
  - blueprintTests
  - blueprintUITests

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - private_outlet
  - sorted_imports

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 270
  error: 400

type_name:
  excluded:
    - blueprintApp

function_body_length:
  warning: 50
  error: 60

identifier_name:
  min_length: 2
  excluded:
    - place_id
    - address_line1
    - address_line2
    - wiki_and_media
    - opening_hours
